-- MySQL Script generated by MySQL Workbench
-- Tue Dec 24 10:25:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Nome do meio` CHAR(1) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Complemento` VARCHAR(5) NULL,
  `Bairro` VARCHAR(20) NULL,
  `Cidade` VARCHAR(20) NULL,
  `Estado` CHAR(2) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veículo` (
  `idVeículo` INT NOT NULL AUTO_INCREMENT,
  `Registro` VARCHAR(45) NOT NULL,
  `Ano de fabricação` DATE NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVeículo`),
  UNIQUE INDEX `Registro_UNIQUE` (`Registro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `MNome` VARCHAR(45) NOT NULL,
  `Código` INT NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(5) NOT NULL,
  `Bairro` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(20) NOT NULL,
  `Estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`idMecânico`),
  UNIQUE INDEX `Código_UNIQUE` (`Código` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de serviço` (
  `idOrdemServiço` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Número` INT NOT NULL,
  `Valor da mão-de-obra` FLOAT NOT NULL,
  `Status` ENUM('Solicitada', 'Em andamento', 'Liberada') NULL DEFAULT 'Solicitada',
  PRIMARY KEY (`idOrdemServiço`),
  UNIQUE INDEX `Número_UNIQUE` (`Número` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `idPeças` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Disponibilidade` ENUM('Disponível', 'Indisponível') NULL DEFAULT 'Disponível',
  PRIMARY KEY (`idPeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças por ordem de serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças por ordem de serviço` (
  `Peças_idPeças` INT NOT NULL,
  `Ordem de serviço_Serviço_idServiço` INT NOT NULL,
  `Quantidade` INT NULL,
  `Preço da peça` FLOAT NULL,
  PRIMARY KEY (`Peças_idPeças`, `Ordem de serviço_Serviço_idServiço`),
  INDEX `fk_Peças_has_Ordem de serviço_Ordem de serviço1_idx` (`Ordem de serviço_Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Peças_has_Ordem de serviço_Peças1_idx` (`Peças_idPeças` ASC) VISIBLE,
  CONSTRAINT `fk_Peças_has_Ordem de serviço_Peças1`
    FOREIGN KEY (`Peças_idPeças`)
    REFERENCES `mydb`.`Peças` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peças_has_Ordem de serviço_Ordem de serviço1`
    FOREIGN KEY (`Ordem de serviço_Serviço_idServiço`)
    REFERENCES `mydb`.`Ordem de serviço` (`idOrdemServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emissão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emissão` (
  `Ordem de serviço_Serviço_idServiço` INT NOT NULL,
  `Ordem de serviço_Mecânico_idMecânico` INT NOT NULL,
  `Mecânico_idMecânico` INT NOT NULL,
  `Data` DATE NOT NULL,
  PRIMARY KEY (`Ordem de serviço_Serviço_idServiço`, `Ordem de serviço_Mecânico_idMecânico`, `Mecânico_idMecânico`),
  INDEX `fk_Ordem de serviço_has_Mecânico_Mecânico1_idx` (`Mecânico_idMecânico` ASC) VISIBLE,
  INDEX `fk_Ordem de serviço_has_Mecânico_Ordem de serviço1_idx` (`Ordem de serviço_Serviço_idServiço` ASC, `Ordem de serviço_Mecânico_idMecânico` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de serviço_has_Mecânico_Ordem de serviço1`
    FOREIGN KEY (`Ordem de serviço_Serviço_idServiço`)
    REFERENCES `mydb`.`Ordem de serviço` (`idOrdemServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de serviço_has_Mecânico_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecânico`)
    REFERENCES `mydb`.`Mecânico` (`idMecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL AUTO_INCREMENT,
  `Ordem de serviço_Serviço_idOrdemServiço` INT NOT NULL,
  `Status do serviço` ENUM('Aguardando ordem de serviço', 'Realizando', 'Concluído') NULL DEFAULT 'Aguardando ordem de serviço',
  `Status do pagamento` FLOAT NOT NULL,
  `Início` DATE NOT NULL,
  `Fim` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Veículo_idVeículo` INT NOT NULL,
  PRIMARY KEY (`idServiço`, `Ordem de serviço_Serviço_idOrdemServiço`, `Cliente_idCliente`, `Veículo_idVeículo`),
  INDEX `fk_Cliente_has_Ordem de serviço_Ordem de serviço1_idx` (`Ordem de serviço_Serviço_idOrdemServiço` ASC) VISIBLE,
  INDEX `fk_Serviço_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Serviço_Veículo1_idx` (`Veículo_idVeículo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Ordem de serviço_Ordem de serviço1`
    FOREIGN KEY (`Ordem de serviço_Serviço_idOrdemServiço`)
    REFERENCES `mydb`.`Ordem de serviço` (`idOrdemServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviço_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
